#!/bin/bash

uvicorn api:app \
    --app-dir /myproject/myproject \
    --host 0.0.0.0 \
    --no-server-header \
    --reload \
    --workers 1 \
    --port 8323

#    --proxy-headers \
#    --forwarded-allow-ips "*" \
